# Generated by Django 2.2.6 on 2019-12-03 04:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung thảo luận')),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/', verbose_name='Hình ảnh')),
                ('curiculum', models.FileField(blank=True, null=True, upload_to='', verbose_name='File đính kèm')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gởi thảo luận')),
                ('view', models.IntegerField(default=0, verbose_name='Số lượt xem')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.BooleanField(default=False, help_text='Trạng thái câu hỏi', verbose_name='Trạng thái')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gởi câu hỏi')),
                ('view', models.IntegerField(default=0, verbose_name='Số lượt xem')),
            ],
        ),
    ]
