# Generated by Django 2.2.6 on 2019-12-08 06:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191203_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung câu hỏi'),
        ),
    ]
