# Generated by Django 2.2.6 on 2019-12-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191208_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giasu.Lesson', verbose_name='Chủ đề'),
        ),
    ]
