# Generated by Django 2.2.6 on 2019-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191210_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Số lượt thích'),
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Số lượt thích'),
        ),
    ]
