# Generated by Django 2.2.6 on 2019-12-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0005_auto_20191221_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='Thảo luận bởi'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='dis_super',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Discussion', verbose_name='Thảo luận cha'),
        ),
    ]
