# Generated by Django 2.2.6 on 2019-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20191223_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='content',
            new_name='dis_content',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='user',
            new_name='dis_user',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='curiculum',
            field=models.FileField(blank=True, null=True, upload_to='forum/', verbose_name='File đính kèm'),
        ),
    ]
