# Generated by Django 2.2.6 on 2019-12-03 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_major', models.CharField(max_length=50, verbose_name='Ngành nghề')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infor', models.TextField(verbose_name='Information about yourself')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')])),
                ('image', models.ImageField(default='profile/default.jpg', null=True, upload_to='profile/')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], null=True)),
                ('point', models.IntegerField(default=0, verbose_name='Point')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major', to='accounts.Major', verbose_name='Chuyên môn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
