# Generated by Django 2.2.6 on 2019-12-03 04:00

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(default='Description', max_length=100)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('pathURL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(help_text='Category of courses', max_length=50)),
                ('cate_description', models.TextField(default='Description', max_length=100)),
                ('cate_image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=50, verbose_name='Họ và tên')),
                ('phone_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Nhập số điện thoại hợp lệ', regex='^0[0-9]{9}$')], verbose_name='Số điện thoại')),
                ('email_contact', models.CharField(max_length=50, verbose_name='Địa chỉ email')),
                ('msg_contact', models.TextField(max_length=100, verbose_name='Nội dung liên hệ')),
                ('status_contact', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Liên hệ',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True, verbose_name='Name of course')),
                ('course_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description of course')),
                ('course_target', models.TextField(verbose_name='Target of course')),
                ('course_require', models.TextField(blank=True, null=True, verbose_name='Requirements of course')),
                ('course_image', models.ImageField(default='courses/default.jpg', help_text="Choice image for course. If you don't choice for course, web will get image 'default'", null=True, upload_to='courses/', verbose_name='Image of course')),
                ('course_duration', models.CharField(max_length=50, verbose_name='Duration of course')),
                ('course_status', models.BooleanField(help_text='Check get active this course', verbose_name='Status of course')),
                ('course_price', models.IntegerField(default=0, verbose_name='Price of course')),
                ('course_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='giasu.Category', verbose_name='Category of course')),
                ('course_students', models.ManyToManyField(blank=True, related_name='students', to='accounts.Profile', verbose_name='Students of course')),
                ('course_teachers', models.ManyToManyField(related_name='teachers', to='accounts.Profile', verbose_name='Teachers of course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='Name of lesson')),
                ('lesson_recap', models.TextField(verbose_name='Content recap of lesson')),
                ('lesson_target', models.TextField(verbose_name='Target of lesson')),
                ('lesson_detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content detail of lesson')),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Image of course')),
                ('lesson_doc', models.FileField(blank=True, null=True, upload_to='', verbose_name='Curriculum doc')),
                ('lesson_video', models.URLField(blank=True, null=True, verbose_name='Curriculum video')),
                ('lesson_status', models.BooleanField(default=False, help_text='Status of the lesson: Active or disactive', verbose_name='Status of the lesson')),
                ('lesson_order', models.IntegerField(default=1, verbose_name='Order of lesson')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='giasu.Course', verbose_name='Course')),
            ],
            options={
                'ordering': ('lesson_order',),
            },
        ),
        migrations.CreateModel(
            name='LibraryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tiên đề')),
                ('image', models.ImageField(upload_to='libraryImage/', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Thư viện ảnh',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('feedback', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answers', models.ManyToManyField(to='giasu.Answer')),
                ('correct_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answer', to='giasu.Answer')),
                ('ques_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_lesson', to='giasu.Lesson', verbose_name='Question of lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_quiz', models.TextField(verbose_name='Mô tả bài kiểm tra')),
                ('status_quiz', models.BooleanField(default=False, verbose_name='Trạng thái bài kiểm tra')),
                ('count_quiz', models.IntegerField(verbose_name='Số lượng câu hỏi')),
                ('time_quiz', models.IntegerField(verbose_name='Thời gian kiểm tra')),
                ('times_quiz', models.IntegerField(verbose_name='Số lượt làm bài')),
                ('lesson_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz', to='giasu.Lesson', verbose_name='Bài học')),
                ('question_quiz', models.ManyToManyField(related_name='quest_quiz', to='giasu.Questions', verbose_name='Câu hỏi')),
                ('user_quiz', models.ManyToManyField(related_name='user_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Danh sách học sinh thi')),
            ],
            options={
                'verbose_name': 'Bài đánh giá kết thúc bài học',
            },
        ),
        migrations.CreateModel(
            name='Review_course',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='giasu.Course', verbose_name='courses')),
                ('star1', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star5', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Đánh giá khóa học *****',
            },
        ),
        migrations.CreateModel(
            name='Review_lesson',
            fields=[
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='giasu.Lesson', verbose_name='Lesson')),
                ('star1', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star5', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Đánh giá bài học *****',
            },
        ),
        migrations.CreateModel(
            name='Student_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('belong_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giasu.Course', verbose_name='Khóa học')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to='accounts.Profile', verbose_name='Người quản lý nhóm')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Nhóm sinh viên')),
                ('member', models.ManyToManyField(blank=True, null=True, to='accounts.Profile', verbose_name='Thành viên nhóm')),
            ],
        ),
        migrations.CreateModel(
            name='Register_Course_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_register', models.CharField(max_length=50, verbose_name='Tên người đăng ký')),
                ('phone_register', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Nhập số điện thoại hợp lệ', regex='^0[0-9]{9}$')], verbose_name='Số điện thoại')),
                ('msg_register', models.TextField(max_length=100, verbose_name='Tin nhắn')),
                ('status_register', models.BooleanField(default=False)),
                ('course_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_register_temp', to='giasu.Course', verbose_name='Khóa học đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký tham gia khóa học của Anonymous User',
            },
        ),
        migrations.CreateModel(
            name='Register_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Trạng thái (đăng ký kích hoạt hoặc chưa kích hoạt)')),
                ('course_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_register', to='giasu.Course', verbose_name='Chọn khóa học')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to='accounts.Profile', verbose_name='Người đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký tham gia khóa học của Authenticated User',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pratice_name', models.CharField(help_text='name of practice', max_length=50)),
                ('practice_detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pratice_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pratice_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='giasu.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=50)),
                ('comment_detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('comment_parent', models.IntegerField(default=0)),
                ('comment_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='giasu.Lesson')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2019, 12, 3, 11, 0, 5, 681889), verbose_name='Ngày học')),
                ('start_time', models.TimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Thời gian kết thúc')),
                ('note', models.TextField(blank=True, max_length=50, null=True, verbose_name='Ghi chú')),
                ('group_impl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.Group', verbose_name='Nhóm thực hiện')),
                ('users_impled', models.ManyToManyField(blank=True, null=True, to='accounts.Profile', verbose_name='Học sinh đã tham gia')),
            ],
            options={
                'verbose_name': 'Lịch học nhóm',
                'verbose_name_plural': 'Lịch học nhóm',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Score_Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('number_of_times', models.IntegerField(default=0)),
                ('quiz_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_score', to='giasu.Quiz_lesson', verbose_name='Bài thi')),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL, verbose_name='Thí sinh')),
            ],
            options={
                'unique_together': {('quiz_lesson', 'user_score')},
            },
        ),
        migrations.CreateModel(
            name='Quiz_lesson_User_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_quiz', ckeditor_uploader.fields.RichTextUploadingField()),
                ('lesson_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_do', to='giasu.Quiz_lesson', verbose_name='Bài thi')),
                ('question_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz_do', to='giasu.Questions', verbose_name='Câu hỏi')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_do', to=settings.AUTH_USER_MODEL, verbose_name='Người thi')),
            ],
            options={
                'unique_together': {('lesson_quiz', 'user_quiz', 'question_quiz')},
            },
        ),
        migrations.CreateModel(
            name='DoPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giasu.Practice', verbose_name='Bài tập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Học sinh')),
            ],
            options={
                'unique_together': {('user', 'practice')},
            },
        ),
    ]
