# Generated by Django 2.2.6 on 2019-12-08 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 8, 13, 12, 57, 918534), verbose_name='Ngày học'),
        ),
    ]
