# Generated by Django 2.2.6 on 2019-12-10 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0002_auto_20191208_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 10, 21, 49, 932691), verbose_name='Ngày học'),
        ),
    ]
