# Generated by Django 2.2.6 on 2019-12-21 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0003_auto_20191210_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 21, 9, 59, 4, 347775), verbose_name='Ngày học'),
        ),
    ]
