# Generated by Django 2.2.6 on 2019-12-23 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0004_auto_20191221_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 23, 10, 24, 35, 639850), verbose_name='Ngày học'),
        ),
    ]
