# Generated by Django 2.2.6 on 2019-12-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0005_auto_20191223_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 25, 14, 17, 38, 639421), verbose_name='Ngày học'),
        ),
    ]
