# Generated by Django 2.2.6 on 2019-12-27 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0006_auto_20191225_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 9, 55, 50, 897820), verbose_name='Ngày học'),
        ),
    ]
