# Generated by Django 2.2.6 on 2019-12-31 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0009_auto_20191231_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 31, 14, 47, 15, 125856), verbose_name='Ngày học'),
        ),
    ]
