# Generated by Django 2.2.6 on 2019-12-31 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giasu', '0012_auto_20191231_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_group',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 31, 15, 39, 32, 782725), verbose_name='Ngày học'),
        ),
    ]
